// Auto-generated contract router
// This file is generated by the contract generation script
// Do not edit manually - regenerate using: bun contract-gen
// In development mode, this file is automatically updated.

export const contract = {
  "health": {
    "v1": {
      "healthCheck": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "GET",
            "path": "/v1/health",
            "tags": [
              "Health"
            ]
          }
        }
      }
    },
    "v2": {
      "healthCheck": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "GET",
            "path": "/v2/health",
            "tags": [
              "Health"
            ]
          }
        }
      }
    }
  },
  "commerce": {
    "store": {
      "listProducts": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "GET",
            "path": "/store/products",
            "summary": "Listar produtos da loja",
            "tags": [
              "Store"
            ]
          }
        }
      },
      "getProduct": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "GET",
            "path": "/store/products/{slug}",
            "summary": "Detalhe do produto",
            "tags": [
              "Store"
            ]
          }
        }
      },
      "listCollections": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "GET",
            "path": "/store/collections",
            "summary": "Listar coleções",
            "tags": [
              "Store"
            ]
          }
        }
      },
      "getCollection": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "GET",
            "path": "/store/collections/{slug}",
            "summary": "Detalhe da coleção",
            "tags": [
              "Store"
            ]
          }
        }
      },
      "getShippingQuote": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "POST",
            "path": "/store/shipping/quote",
            "summary": "Cotação de frete",
            "tags": [
              "Store"
            ]
          }
        }
      },
      "createOrder": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "POST",
            "path": "/store/orders",
            "summary": "Criar pedido",
            "tags": [
              "Store"
            ]
          }
        }
      },
      "getOrder": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "GET",
            "path": "/store/orders/{id}",
            "summary": "Detalhe do pedido",
            "tags": [
              "Store"
            ]
          }
        }
      },
      "listMyOrders": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "GET",
            "path": "/store/orders/me",
            "summary": "Meus pedidos",
            "tags": [
              "Store"
            ]
          }
        }
      }
    },
    "admin": {
      "listProducts": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "GET",
            "path": "/admin/products",
            "summary": "Listar produtos (admin)",
            "tags": [
              "Admin"
            ]
          }
        }
      },
      "createProduct": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "POST",
            "path": "/admin/products",
            "summary": "Criar produto",
            "tags": [
              "Admin"
            ]
          }
        }
      },
      "updateProduct": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "PATCH",
            "path": "/admin/products/{id}",
            "summary": "Atualizar produto",
            "tags": [
              "Admin"
            ]
          }
        }
      },
      "listInventory": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "GET",
            "path": "/admin/inventory",
            "summary": "Listar estoque",
            "tags": [
              "Admin"
            ]
          }
        }
      },
      "listLowStockAlerts": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "GET",
            "path": "/admin/inventory/low-stock",
            "summary": "Alertas de estoque baixo",
            "tags": [
              "Admin"
            ]
          }
        }
      },
      "listInventoryMovements": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "GET",
            "path": "/admin/inventory/movements",
            "summary": "Histórico de movimentações",
            "tags": [
              "Admin"
            ]
          }
        }
      },
      "receiveInventory": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "POST",
            "path": "/admin/inventory/receive",
            "summary": "Entrada de mercadoria",
            "tags": [
              "Admin"
            ]
          }
        }
      },
      "transferInventory": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "POST",
            "path": "/admin/inventory/transfer",
            "summary": "Transferir entre depósitos",
            "tags": [
              "Admin"
            ]
          }
        }
      },
      "exportInventoryCsv": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "GET",
            "path": "/admin/inventory/export",
            "summary": "Exportar estoque CSV",
            "tags": [
              "Admin"
            ]
          }
        }
      },
      "importInventoryCsv": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "POST",
            "path": "/admin/inventory/import",
            "summary": "Importar estoque CSV",
            "tags": [
              "Admin"
            ]
          }
        }
      },
      "listWarehouses": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "GET",
            "path": "/admin/warehouses",
            "summary": "Listar depósitos",
            "tags": [
              "Admin"
            ]
          }
        }
      },
      "createWarehouse": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "POST",
            "path": "/admin/warehouses",
            "summary": "Criar depósito",
            "tags": [
              "Admin"
            ]
          }
        }
      },
      "adjustInventory": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "POST",
            "path": "/admin/inventory/adjust",
            "summary": "Ajustar estoque",
            "tags": [
              "Admin"
            ]
          }
        }
      },
      "listOrders": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "GET",
            "path": "/admin/orders",
            "summary": "Listar pedidos",
            "tags": [
              "Admin"
            ]
          }
        }
      },
      "getOrder": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "GET",
            "path": "/admin/orders/{id}",
            "summary": "Detalhe do pedido (admin)",
            "tags": [
              "Admin"
            ]
          }
        }
      },
      "updateOrderStatus": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "PATCH",
            "path": "/admin/orders/{id}/status",
            "summary": "Atualizar status do pedido",
            "tags": [
              "Admin"
            ]
          }
        }
      },
      "uploadProductImage": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "POST",
            "path": "/admin/products/images",
            "summary": "Upload de imagem de produto",
            "tags": [
              "Admin"
            ]
          }
        }
      },
      "deleteProductImage": {
        "~orpc": {
          "errorMap": {},
          "meta": {},
          "route": {
            "method": "DELETE",
            "path": "/admin/products/images/{id}",
            "summary": "Remover imagem de produto",
            "tags": [
              "Admin"
            ]
          }
        }
      }
    }
  }
} as const;
