import fs from "node:fs";

import { appRouter } from "@lindaflor/api/routers";
import { minifyContractRouter } from "@orpc/contract";
import { Effect } from "effect";

const minifiedRouter = minifyContractRouter(appRouter);

const contractContent = `// Auto-generated contract router
// This file is generated by the contract generation script
// Do not edit manually - regenerate using: bun contract-gen
// In development mode, this file is automatically updated.

export const contract = ${JSON.stringify(minifiedRouter, null, 2)} as const;
`;

const outputPath = "./src/contract/index.gen.ts";
const existingContent = fs.existsSync(outputPath)
  ? fs.readFileSync(outputPath, "utf-8")
  : null;

if (existingContent !== contractContent) {
  fs.writeFileSync(outputPath, contractContent);
  Effect.runSync(Effect.log("Contract generated successfully"));
} else {
  Effect.runSync(Effect.log("Contract is up to date"));
}

process.exit(0);
