/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as TrocasDevolucoesRouteImport } from './routes/trocas-devolucoes'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PoliticaPrivacidadeRouteImport } from './routes/politica-privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutosIndexRouteImport } from './routes/produtos/index'
import { Route as ExemplosIndexRouteImport } from './routes/exemplos/index'
import { Route as ColecoesIndexRouteImport } from './routes/colecoes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProdutosSlugRouteImport } from './routes/produtos/$slug'
import { Route as PedidoIdRouteImport } from './routes/pedido/$id'
import { Route as ExemplosEditorialRouteImport } from './routes/exemplos/editorial'
import { Route as ExemplosBossaNovaRouteImport } from './routes/exemplos/bossa-nova'
import { Route as ExemplosBodoniRouteImport } from './routes/exemplos/bodoni'
import { Route as ContaPedidosRouteImport } from './routes/conta/pedidos'
import { Route as ColecoesSlugRouteImport } from './routes/colecoes/$slug'
import { Route as AdminProdutosIndexRouteImport } from './routes/admin/produtos/index'
import { Route as AdminPedidosIndexRouteImport } from './routes/admin/pedidos/index'
import { Route as AdminEstoqueIndexRouteImport } from './routes/admin/estoque/index'
import { Route as authSettingsIndexRouteImport } from './routes/(auth)/settings/index'
import { Route as authPermissionsIndexRouteImport } from './routes/(auth)/permissions/index'
import { Route as authDashboardIndexRouteImport } from './routes/(auth)/dashboard/index'
import { Route as AdminProdutosNovoRouteImport } from './routes/admin/produtos/novo'
import { Route as AdminProdutosIdRouteImport } from './routes/admin/produtos/$id'
import { Route as AdminPedidosIdRouteImport } from './routes/admin/pedidos/$id'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocasDevolucoesRoute = TrocasDevolucoesRouteImport.update({
  id: '/trocas-devolucoes',
  path: '/trocas-devolucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadeRoute = PoliticaPrivacidadeRouteImport.update({
  id: '/politica-privacidade',
  path: '/politica-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExemplosIndexRoute = ExemplosIndexRouteImport.update({
  id: '/exemplos/',
  path: '/exemplos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecoesIndexRoute = ColecoesIndexRouteImport.update({
  id: '/colecoes/',
  path: '/colecoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/produtos/$slug',
  path: '/produtos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExemplosEditorialRoute = ExemplosEditorialRouteImport.update({
  id: '/exemplos/editorial',
  path: '/exemplos/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ExemplosBossaNovaRoute = ExemplosBossaNovaRouteImport.update({
  id: '/exemplos/bossa-nova',
  path: '/exemplos/bossa-nova',
  getParentRoute: () => rootRouteImport,
} as any)
const ExemplosBodoniRoute = ExemplosBodoniRouteImport.update({
  id: '/exemplos/bodoni',
  path: '/exemplos/bodoni',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaPedidosRoute = ContaPedidosRouteImport.update({
  id: '/conta/pedidos',
  path: '/conta/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecoesSlugRoute = ColecoesSlugRouteImport.update({
  id: '/colecoes/$slug',
  path: '/colecoes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosIndexRoute = AdminProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPedidosIndexRoute = AdminPedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEstoqueIndexRoute = AdminEstoqueIndexRouteImport.update({
  id: '/estoque/',
  path: '/estoque/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const authSettingsIndexRoute = authSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => authRouteRoute,
} as any)
const authPermissionsIndexRoute = authPermissionsIndexRouteImport.update({
  id: '/permissions/',
  path: '/permissions/',
  getParentRoute: () => authRouteRoute,
} as any)
const authDashboardIndexRoute = authDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => authRouteRoute,
} as any)
const AdminProdutosNovoRoute = AdminProdutosNovoRouteImport.update({
  id: '/produtos/novo',
  path: '/produtos/novo',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProdutosIdRoute = AdminProdutosIdRouteImport.update({
  id: '/produtos/$id',
  path: '/produtos/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPedidosIdRoute = AdminPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/carrinho': typeof CarrinhoRoute
  '/check-email': typeof CheckEmailRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/trocas-devolucoes': typeof TrocasDevolucoesRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/colecoes/$slug': typeof ColecoesSlugRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/exemplos/bodoni': typeof ExemplosBodoniRoute
  '/exemplos/bossa-nova': typeof ExemplosBossaNovaRoute
  '/exemplos/editorial': typeof ExemplosEditorialRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/colecoes/': typeof ColecoesIndexRoute
  '/exemplos/': typeof ExemplosIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/dashboard/': typeof authDashboardIndexRoute
  '/permissions/': typeof authPermissionsIndexRoute
  '/settings/': typeof authSettingsIndexRoute
  '/admin/estoque/': typeof AdminEstoqueIndexRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/carrinho': typeof CarrinhoRoute
  '/check-email': typeof CheckEmailRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/trocas-devolucoes': typeof TrocasDevolucoesRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/colecoes/$slug': typeof ColecoesSlugRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/exemplos/bodoni': typeof ExemplosBodoniRoute
  '/exemplos/bossa-nova': typeof ExemplosBossaNovaRoute
  '/exemplos/editorial': typeof ExemplosEditorialRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/admin': typeof AdminIndexRoute
  '/colecoes': typeof ColecoesIndexRoute
  '/exemplos': typeof ExemplosIndexRoute
  '/produtos': typeof ProdutosIndexRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/dashboard': typeof authDashboardIndexRoute
  '/permissions': typeof authPermissionsIndexRoute
  '/settings': typeof authSettingsIndexRoute
  '/admin/estoque': typeof AdminEstoqueIndexRoute
  '/admin/pedidos': typeof AdminPedidosIndexRoute
  '/admin/produtos': typeof AdminProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/carrinho': typeof CarrinhoRoute
  '/check-email': typeof CheckEmailRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/trocas-devolucoes': typeof TrocasDevolucoesRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/colecoes/$slug': typeof ColecoesSlugRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/exemplos/bodoni': typeof ExemplosBodoniRoute
  '/exemplos/bossa-nova': typeof ExemplosBossaNovaRoute
  '/exemplos/editorial': typeof ExemplosEditorialRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/colecoes/': typeof ColecoesIndexRoute
  '/exemplos/': typeof ExemplosIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/(auth)/dashboard/': typeof authDashboardIndexRoute
  '/(auth)/permissions/': typeof authPermissionsIndexRoute
  '/(auth)/settings/': typeof authSettingsIndexRoute
  '/admin/estoque/': typeof AdminEstoqueIndexRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/accept-invitation'
    | '/carrinho'
    | '/check-email'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/politica-privacidade'
    | '/reset-password'
    | '/termos'
    | '/trocas-devolucoes'
    | '/two-factor'
    | '/verify-email'
    | '/colecoes/$slug'
    | '/conta/pedidos'
    | '/exemplos/bodoni'
    | '/exemplos/bossa-nova'
    | '/exemplos/editorial'
    | '/pedido/$id'
    | '/produtos/$slug'
    | '/admin/'
    | '/colecoes/'
    | '/exemplos/'
    | '/produtos/'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/dashboard/'
    | '/permissions/'
    | '/settings/'
    | '/admin/estoque/'
    | '/admin/pedidos/'
    | '/admin/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/carrinho'
    | '/check-email'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/politica-privacidade'
    | '/reset-password'
    | '/termos'
    | '/trocas-devolucoes'
    | '/two-factor'
    | '/verify-email'
    | '/colecoes/$slug'
    | '/conta/pedidos'
    | '/exemplos/bodoni'
    | '/exemplos/bossa-nova'
    | '/exemplos/editorial'
    | '/pedido/$id'
    | '/produtos/$slug'
    | '/admin'
    | '/colecoes'
    | '/exemplos'
    | '/produtos'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/dashboard'
    | '/permissions'
    | '/settings'
    | '/admin/estoque'
    | '/admin/pedidos'
    | '/admin/produtos'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/admin'
    | '/accept-invitation'
    | '/carrinho'
    | '/check-email'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/politica-privacidade'
    | '/reset-password'
    | '/termos'
    | '/trocas-devolucoes'
    | '/two-factor'
    | '/verify-email'
    | '/colecoes/$slug'
    | '/conta/pedidos'
    | '/exemplos/bodoni'
    | '/exemplos/bossa-nova'
    | '/exemplos/editorial'
    | '/pedido/$id'
    | '/produtos/$slug'
    | '/admin/'
    | '/colecoes/'
    | '/exemplos/'
    | '/produtos/'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/(auth)/dashboard/'
    | '/(auth)/permissions/'
    | '/(auth)/settings/'
    | '/admin/estoque/'
    | '/admin/pedidos/'
    | '/admin/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckEmailRoute: typeof CheckEmailRoute
  CheckoutRoute: typeof CheckoutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PoliticaPrivacidadeRoute: typeof PoliticaPrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermosRoute: typeof TermosRoute
  TrocasDevolucoesRoute: typeof TrocasDevolucoesRoute
  TwoFactorRoute: typeof TwoFactorRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ColecoesSlugRoute: typeof ColecoesSlugRoute
  ContaPedidosRoute: typeof ContaPedidosRoute
  ExemplosBodoniRoute: typeof ExemplosBodoniRoute
  ExemplosBossaNovaRoute: typeof ExemplosBossaNovaRoute
  ExemplosEditorialRoute: typeof ExemplosEditorialRoute
  PedidoIdRoute: typeof PedidoIdRoute
  ProdutosSlugRoute: typeof ProdutosSlugRoute
  ColecoesIndexRoute: typeof ColecoesIndexRoute
  ExemplosIndexRoute: typeof ExemplosIndexRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocas-devolucoes': {
      id: '/trocas-devolucoes'
      path: '/trocas-devolucoes'
      fullPath: '/trocas-devolucoes'
      preLoaderRoute: typeof TrocasDevolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidade': {
      id: '/politica-privacidade'
      path: '/politica-privacidade'
      fullPath: '/politica-privacidade'
      preLoaderRoute: typeof PoliticaPrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exemplos/': {
      id: '/exemplos/'
      path: '/exemplos'
      fullPath: '/exemplos/'
      preLoaderRoute: typeof ExemplosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecoes/': {
      id: '/colecoes/'
      path: '/colecoes'
      fullPath: '/colecoes/'
      preLoaderRoute: typeof ColecoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/produtos/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exemplos/editorial': {
      id: '/exemplos/editorial'
      path: '/exemplos/editorial'
      fullPath: '/exemplos/editorial'
      preLoaderRoute: typeof ExemplosEditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exemplos/bossa-nova': {
      id: '/exemplos/bossa-nova'
      path: '/exemplos/bossa-nova'
      fullPath: '/exemplos/bossa-nova'
      preLoaderRoute: typeof ExemplosBossaNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exemplos/bodoni': {
      id: '/exemplos/bodoni'
      path: '/exemplos/bodoni'
      fullPath: '/exemplos/bodoni'
      preLoaderRoute: typeof ExemplosBodoniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/pedidos': {
      id: '/conta/pedidos'
      path: '/conta/pedidos'
      fullPath: '/conta/pedidos'
      preLoaderRoute: typeof ContaPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecoes/$slug': {
      id: '/colecoes/$slug'
      path: '/colecoes/$slug'
      fullPath: '/colecoes/$slug'
      preLoaderRoute: typeof ColecoesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos/': {
      id: '/admin/produtos/'
      path: '/produtos'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AdminProdutosIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pedidos/': {
      id: '/admin/pedidos/'
      path: '/pedidos'
      fullPath: '/admin/pedidos/'
      preLoaderRoute: typeof AdminPedidosIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/estoque/': {
      id: '/admin/estoque/'
      path: '/estoque'
      fullPath: '/admin/estoque/'
      preLoaderRoute: typeof AdminEstoqueIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(auth)/settings/': {
      id: '/(auth)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof authSettingsIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/permissions/': {
      id: '/(auth)/permissions/'
      path: '/permissions'
      fullPath: '/permissions/'
      preLoaderRoute: typeof authPermissionsIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/dashboard/': {
      id: '/(auth)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authDashboardIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/admin/produtos/novo': {
      id: '/admin/produtos/novo'
      path: '/produtos/novo'
      fullPath: '/admin/produtos/novo'
      preLoaderRoute: typeof AdminProdutosNovoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/produtos/$id': {
      id: '/admin/produtos/$id'
      path: '/produtos/$id'
      fullPath: '/admin/produtos/$id'
      preLoaderRoute: typeof AdminProdutosIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pedidos/$id': {
      id: '/admin/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AdminPedidosIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authDashboardIndexRoute: typeof authDashboardIndexRoute
  authPermissionsIndexRoute: typeof authPermissionsIndexRoute
  authSettingsIndexRoute: typeof authSettingsIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authDashboardIndexRoute: authDashboardIndexRoute,
  authPermissionsIndexRoute: authPermissionsIndexRoute,
  authSettingsIndexRoute: authSettingsIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPedidosIdRoute: typeof AdminPedidosIdRoute
  AdminProdutosIdRoute: typeof AdminProdutosIdRoute
  AdminProdutosNovoRoute: typeof AdminProdutosNovoRoute
  AdminEstoqueIndexRoute: typeof AdminEstoqueIndexRoute
  AdminPedidosIndexRoute: typeof AdminPedidosIndexRoute
  AdminProdutosIndexRoute: typeof AdminProdutosIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminPedidosIdRoute: AdminPedidosIdRoute,
  AdminProdutosIdRoute: AdminProdutosIdRoute,
  AdminProdutosNovoRoute: AdminProdutosNovoRoute,
  AdminEstoqueIndexRoute: AdminEstoqueIndexRoute,
  AdminPedidosIndexRoute: AdminPedidosIndexRoute,
  AdminProdutosIndexRoute: AdminProdutosIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckEmailRoute: CheckEmailRoute,
  CheckoutRoute: CheckoutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PoliticaPrivacidadeRoute: PoliticaPrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermosRoute: TermosRoute,
  TrocasDevolucoesRoute: TrocasDevolucoesRoute,
  TwoFactorRoute: TwoFactorRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ColecoesSlugRoute: ColecoesSlugRoute,
  ContaPedidosRoute: ContaPedidosRoute,
  ExemplosBodoniRoute: ExemplosBodoniRoute,
  ExemplosBossaNovaRoute: ExemplosBossaNovaRoute,
  ExemplosEditorialRoute: ExemplosEditorialRoute,
  PedidoIdRoute: PedidoIdRoute,
  ProdutosSlugRoute: ProdutosSlugRoute,
  ColecoesIndexRoute: ColecoesIndexRoute,
  ExemplosIndexRoute: ExemplosIndexRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
