/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as TrocasDevolucoesRouteImport } from './routes/trocas-devolucoes'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PoliticaPrivacidadeRouteImport } from './routes/politica-privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutosIndexRouteImport } from './routes/produtos/index'
import { Route as ExemplosIndexRouteImport } from './routes/exemplos/index'
import { Route as ColecoesIndexRouteImport } from './routes/colecoes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProdutosSlugRouteImport } from './routes/produtos/$slug'
import { Route as PedidoIdRouteImport } from './routes/pedido/$id'
import { Route as ExemplosEditorialRouteImport } from './routes/exemplos/editorial'
import { Route as ExemplosBossaNovaRouteImport } from './routes/exemplos/bossa-nova'
import { Route as ExemplosBodoniRouteImport } from './routes/exemplos/bodoni'
import { Route as CurriculumSubmitRouteImport } from './routes/curriculum/submit'
import { Route as ContaPedidosRouteImport } from './routes/conta/pedidos'
import { Route as ColecoesSlugRouteImport } from './routes/colecoes/$slug'
import { Route as authCurriculumRouteRouteImport } from './routes/(auth)/curriculum/route'
import { Route as AdminProdutosIndexRouteImport } from './routes/admin/produtos/index'
import { Route as AdminPedidosIndexRouteImport } from './routes/admin/pedidos/index'
import { Route as AdminEstoqueIndexRouteImport } from './routes/admin/estoque/index'
import { Route as authTrainingIndexRouteImport } from './routes/(auth)/training/index'
import { Route as authTankagesIndexRouteImport } from './routes/(auth)/tankages/index'
import { Route as authSettingsIndexRouteImport } from './routes/(auth)/settings/index'
import { Route as authPermissionsIndexRouteImport } from './routes/(auth)/permissions/index'
import { Route as authDashboardIndexRouteImport } from './routes/(auth)/dashboard/index'
import { Route as authCurriculumIndexRouteImport } from './routes/(auth)/curriculum/index'
import { Route as authCadastrosIndexRouteImport } from './routes/(auth)/cadastros/index'
import { Route as authArqueacaoIndexRouteImport } from './routes/(auth)/arqueacao/index'
import { Route as AdminProdutosNovoRouteImport } from './routes/admin/produtos/novo'
import { Route as AdminProdutosIdRouteImport } from './routes/admin/produtos/$id'
import { Route as AdminPedidosIdRouteImport } from './routes/admin/pedidos/$id'
import { Route as authTrainingManageRouteImport } from './routes/(auth)/training/manage'
import { Route as authCurriculumIdRouteImport } from './routes/(auth)/curriculum/$id'
import { Route as authTankagesTankIdIndexRouteImport } from './routes/(auth)/tankages/$tankId/index'
import { Route as authTrainingCoursesNewRouteImport } from './routes/(auth)/training/courses/new'
import { Route as authTrainingCoursesIdRouteImport } from './routes/(auth)/training/courses/$id'
import { Route as authTankagesTankIdAnalisesLaboratorioRouteImport } from './routes/(auth)/tankages/$tankId/analises-laboratorio'
import { Route as authTankagesTankIdDateRouteImport } from './routes/(auth)/tankages/$tankId/$date'
import { Route as authTrainingCoursesIdIndexRouteImport } from './routes/(auth)/training/courses/$id/index'
import { Route as authTrainingCoursesIdManageRouteImport } from './routes/(auth)/training/courses/$id/manage'
import { Route as authTrainingCoursesIdCertificateRouteImport } from './routes/(auth)/training/courses/$id/certificate'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocasDevolucoesRoute = TrocasDevolucoesRouteImport.update({
  id: '/trocas-devolucoes',
  path: '/trocas-devolucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadeRoute = PoliticaPrivacidadeRouteImport.update({
  id: '/politica-privacidade',
  path: '/politica-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExemplosIndexRoute = ExemplosIndexRouteImport.update({
  id: '/exemplos/',
  path: '/exemplos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecoesIndexRoute = ColecoesIndexRouteImport.update({
  id: '/colecoes/',
  path: '/colecoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/produtos/$slug',
  path: '/produtos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExemplosEditorialRoute = ExemplosEditorialRouteImport.update({
  id: '/exemplos/editorial',
  path: '/exemplos/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ExemplosBossaNovaRoute = ExemplosBossaNovaRouteImport.update({
  id: '/exemplos/bossa-nova',
  path: '/exemplos/bossa-nova',
  getParentRoute: () => rootRouteImport,
} as any)
const ExemplosBodoniRoute = ExemplosBodoniRouteImport.update({
  id: '/exemplos/bodoni',
  path: '/exemplos/bodoni',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumSubmitRoute = CurriculumSubmitRouteImport.update({
  id: '/curriculum/submit',
  path: '/curriculum/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaPedidosRoute = ContaPedidosRouteImport.update({
  id: '/conta/pedidos',
  path: '/conta/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecoesSlugRoute = ColecoesSlugRouteImport.update({
  id: '/colecoes/$slug',
  path: '/colecoes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const authCurriculumRouteRoute = authCurriculumRouteRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => authRouteRoute,
} as any)
const AdminProdutosIndexRoute = AdminProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPedidosIndexRoute = AdminPedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEstoqueIndexRoute = AdminEstoqueIndexRouteImport.update({
  id: '/estoque/',
  path: '/estoque/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const authTrainingIndexRoute = authTrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => authRouteRoute,
} as any)
const authTankagesIndexRoute = authTankagesIndexRouteImport.update({
  id: '/tankages/',
  path: '/tankages/',
  getParentRoute: () => authRouteRoute,
} as any)
const authSettingsIndexRoute = authSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => authRouteRoute,
} as any)
const authPermissionsIndexRoute = authPermissionsIndexRouteImport.update({
  id: '/permissions/',
  path: '/permissions/',
  getParentRoute: () => authRouteRoute,
} as any)
const authDashboardIndexRoute = authDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => authRouteRoute,
} as any)
const authCurriculumIndexRoute = authCurriculumIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authCurriculumRouteRoute,
} as any)
const authCadastrosIndexRoute = authCadastrosIndexRouteImport.update({
  id: '/cadastros/',
  path: '/cadastros/',
  getParentRoute: () => authRouteRoute,
} as any)
const authArqueacaoIndexRoute = authArqueacaoIndexRouteImport.update({
  id: '/arqueacao/',
  path: '/arqueacao/',
  getParentRoute: () => authRouteRoute,
} as any)
const AdminProdutosNovoRoute = AdminProdutosNovoRouteImport.update({
  id: '/produtos/novo',
  path: '/produtos/novo',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProdutosIdRoute = AdminProdutosIdRouteImport.update({
  id: '/produtos/$id',
  path: '/produtos/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPedidosIdRoute = AdminPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const authTrainingManageRoute = authTrainingManageRouteImport.update({
  id: '/training/manage',
  path: '/training/manage',
  getParentRoute: () => authRouteRoute,
} as any)
const authCurriculumIdRoute = authCurriculumIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => authCurriculumRouteRoute,
} as any)
const authTankagesTankIdIndexRoute = authTankagesTankIdIndexRouteImport.update({
  id: '/tankages/$tankId/',
  path: '/tankages/$tankId/',
  getParentRoute: () => authRouteRoute,
} as any)
const authTrainingCoursesNewRoute = authTrainingCoursesNewRouteImport.update({
  id: '/training/courses/new',
  path: '/training/courses/new',
  getParentRoute: () => authRouteRoute,
} as any)
const authTrainingCoursesIdRoute = authTrainingCoursesIdRouteImport.update({
  id: '/training/courses/$id',
  path: '/training/courses/$id',
  getParentRoute: () => authRouteRoute,
} as any)
const authTankagesTankIdAnalisesLaboratorioRoute =
  authTankagesTankIdAnalisesLaboratorioRouteImport.update({
    id: '/tankages/$tankId/analises-laboratorio',
    path: '/tankages/$tankId/analises-laboratorio',
    getParentRoute: () => authRouteRoute,
  } as any)
const authTankagesTankIdDateRoute = authTankagesTankIdDateRouteImport.update({
  id: '/tankages/$tankId/$date',
  path: '/tankages/$tankId/$date',
  getParentRoute: () => authRouteRoute,
} as any)
const authTrainingCoursesIdIndexRoute =
  authTrainingCoursesIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authTrainingCoursesIdRoute,
  } as any)
const authTrainingCoursesIdManageRoute =
  authTrainingCoursesIdManageRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => authTrainingCoursesIdRoute,
  } as any)
const authTrainingCoursesIdCertificateRoute =
  authTrainingCoursesIdCertificateRouteImport.update({
    id: '/certificate',
    path: '/certificate',
    getParentRoute: () => authTrainingCoursesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/carrinho': typeof CarrinhoRoute
  '/check-email': typeof CheckEmailRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/trocas-devolucoes': typeof TrocasDevolucoesRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/curriculum': typeof authCurriculumRouteRouteWithChildren
  '/colecoes/$slug': typeof ColecoesSlugRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/curriculum/submit': typeof CurriculumSubmitRoute
  '/exemplos/bodoni': typeof ExemplosBodoniRoute
  '/exemplos/bossa-nova': typeof ExemplosBossaNovaRoute
  '/exemplos/editorial': typeof ExemplosEditorialRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/colecoes/': typeof ColecoesIndexRoute
  '/exemplos/': typeof ExemplosIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/curriculum/$id': typeof authCurriculumIdRoute
  '/training/manage': typeof authTrainingManageRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/arqueacao/': typeof authArqueacaoIndexRoute
  '/cadastros/': typeof authCadastrosIndexRoute
  '/curriculum/': typeof authCurriculumIndexRoute
  '/dashboard/': typeof authDashboardIndexRoute
  '/permissions/': typeof authPermissionsIndexRoute
  '/settings/': typeof authSettingsIndexRoute
  '/tankages/': typeof authTankagesIndexRoute
  '/training/': typeof authTrainingIndexRoute
  '/admin/estoque/': typeof AdminEstoqueIndexRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/tankages/$tankId/$date': typeof authTankagesTankIdDateRoute
  '/tankages/$tankId/analises-laboratorio': typeof authTankagesTankIdAnalisesLaboratorioRoute
  '/training/courses/$id': typeof authTrainingCoursesIdRouteWithChildren
  '/training/courses/new': typeof authTrainingCoursesNewRoute
  '/tankages/$tankId/': typeof authTankagesTankIdIndexRoute
  '/training/courses/$id/certificate': typeof authTrainingCoursesIdCertificateRoute
  '/training/courses/$id/manage': typeof authTrainingCoursesIdManageRoute
  '/training/courses/$id/': typeof authTrainingCoursesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/carrinho': typeof CarrinhoRoute
  '/check-email': typeof CheckEmailRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/trocas-devolucoes': typeof TrocasDevolucoesRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/colecoes/$slug': typeof ColecoesSlugRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/curriculum/submit': typeof CurriculumSubmitRoute
  '/exemplos/bodoni': typeof ExemplosBodoniRoute
  '/exemplos/bossa-nova': typeof ExemplosBossaNovaRoute
  '/exemplos/editorial': typeof ExemplosEditorialRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/admin': typeof AdminIndexRoute
  '/colecoes': typeof ColecoesIndexRoute
  '/exemplos': typeof ExemplosIndexRoute
  '/produtos': typeof ProdutosIndexRoute
  '/curriculum/$id': typeof authCurriculumIdRoute
  '/training/manage': typeof authTrainingManageRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/arqueacao': typeof authArqueacaoIndexRoute
  '/cadastros': typeof authCadastrosIndexRoute
  '/curriculum': typeof authCurriculumIndexRoute
  '/dashboard': typeof authDashboardIndexRoute
  '/permissions': typeof authPermissionsIndexRoute
  '/settings': typeof authSettingsIndexRoute
  '/tankages': typeof authTankagesIndexRoute
  '/training': typeof authTrainingIndexRoute
  '/admin/estoque': typeof AdminEstoqueIndexRoute
  '/admin/pedidos': typeof AdminPedidosIndexRoute
  '/admin/produtos': typeof AdminProdutosIndexRoute
  '/tankages/$tankId/$date': typeof authTankagesTankIdDateRoute
  '/tankages/$tankId/analises-laboratorio': typeof authTankagesTankIdAnalisesLaboratorioRoute
  '/training/courses/new': typeof authTrainingCoursesNewRoute
  '/tankages/$tankId': typeof authTankagesTankIdIndexRoute
  '/training/courses/$id/certificate': typeof authTrainingCoursesIdCertificateRoute
  '/training/courses/$id/manage': typeof authTrainingCoursesIdManageRoute
  '/training/courses/$id': typeof authTrainingCoursesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/carrinho': typeof CarrinhoRoute
  '/check-email': typeof CheckEmailRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/trocas-devolucoes': typeof TrocasDevolucoesRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/(auth)/curriculum': typeof authCurriculumRouteRouteWithChildren
  '/colecoes/$slug': typeof ColecoesSlugRoute
  '/conta/pedidos': typeof ContaPedidosRoute
  '/curriculum/submit': typeof CurriculumSubmitRoute
  '/exemplos/bodoni': typeof ExemplosBodoniRoute
  '/exemplos/bossa-nova': typeof ExemplosBossaNovaRoute
  '/exemplos/editorial': typeof ExemplosEditorialRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/colecoes/': typeof ColecoesIndexRoute
  '/exemplos/': typeof ExemplosIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/(auth)/curriculum/$id': typeof authCurriculumIdRoute
  '/(auth)/training/manage': typeof authTrainingManageRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/(auth)/arqueacao/': typeof authArqueacaoIndexRoute
  '/(auth)/cadastros/': typeof authCadastrosIndexRoute
  '/(auth)/curriculum/': typeof authCurriculumIndexRoute
  '/(auth)/dashboard/': typeof authDashboardIndexRoute
  '/(auth)/permissions/': typeof authPermissionsIndexRoute
  '/(auth)/settings/': typeof authSettingsIndexRoute
  '/(auth)/tankages/': typeof authTankagesIndexRoute
  '/(auth)/training/': typeof authTrainingIndexRoute
  '/admin/estoque/': typeof AdminEstoqueIndexRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/(auth)/tankages/$tankId/$date': typeof authTankagesTankIdDateRoute
  '/(auth)/tankages/$tankId/analises-laboratorio': typeof authTankagesTankIdAnalisesLaboratorioRoute
  '/(auth)/training/courses/$id': typeof authTrainingCoursesIdRouteWithChildren
  '/(auth)/training/courses/new': typeof authTrainingCoursesNewRoute
  '/(auth)/tankages/$tankId/': typeof authTankagesTankIdIndexRoute
  '/(auth)/training/courses/$id/certificate': typeof authTrainingCoursesIdCertificateRoute
  '/(auth)/training/courses/$id/manage': typeof authTrainingCoursesIdManageRoute
  '/(auth)/training/courses/$id/': typeof authTrainingCoursesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/accept-invitation'
    | '/carrinho'
    | '/check-email'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/politica-privacidade'
    | '/reset-password'
    | '/termos'
    | '/trocas-devolucoes'
    | '/two-factor'
    | '/verify-email'
    | '/curriculum'
    | '/colecoes/$slug'
    | '/conta/pedidos'
    | '/curriculum/submit'
    | '/exemplos/bodoni'
    | '/exemplos/bossa-nova'
    | '/exemplos/editorial'
    | '/pedido/$id'
    | '/produtos/$slug'
    | '/admin/'
    | '/colecoes/'
    | '/exemplos/'
    | '/produtos/'
    | '/curriculum/$id'
    | '/training/manage'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/arqueacao/'
    | '/cadastros/'
    | '/curriculum/'
    | '/dashboard/'
    | '/permissions/'
    | '/settings/'
    | '/tankages/'
    | '/training/'
    | '/admin/estoque/'
    | '/admin/pedidos/'
    | '/admin/produtos/'
    | '/tankages/$tankId/$date'
    | '/tankages/$tankId/analises-laboratorio'
    | '/training/courses/$id'
    | '/training/courses/new'
    | '/tankages/$tankId/'
    | '/training/courses/$id/certificate'
    | '/training/courses/$id/manage'
    | '/training/courses/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/carrinho'
    | '/check-email'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/politica-privacidade'
    | '/reset-password'
    | '/termos'
    | '/trocas-devolucoes'
    | '/two-factor'
    | '/verify-email'
    | '/colecoes/$slug'
    | '/conta/pedidos'
    | '/curriculum/submit'
    | '/exemplos/bodoni'
    | '/exemplos/bossa-nova'
    | '/exemplos/editorial'
    | '/pedido/$id'
    | '/produtos/$slug'
    | '/admin'
    | '/colecoes'
    | '/exemplos'
    | '/produtos'
    | '/curriculum/$id'
    | '/training/manage'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/arqueacao'
    | '/cadastros'
    | '/curriculum'
    | '/dashboard'
    | '/permissions'
    | '/settings'
    | '/tankages'
    | '/training'
    | '/admin/estoque'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/tankages/$tankId/$date'
    | '/tankages/$tankId/analises-laboratorio'
    | '/training/courses/new'
    | '/tankages/$tankId'
    | '/training/courses/$id/certificate'
    | '/training/courses/$id/manage'
    | '/training/courses/$id'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/admin'
    | '/accept-invitation'
    | '/carrinho'
    | '/check-email'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/politica-privacidade'
    | '/reset-password'
    | '/termos'
    | '/trocas-devolucoes'
    | '/two-factor'
    | '/verify-email'
    | '/(auth)/curriculum'
    | '/colecoes/$slug'
    | '/conta/pedidos'
    | '/curriculum/submit'
    | '/exemplos/bodoni'
    | '/exemplos/bossa-nova'
    | '/exemplos/editorial'
    | '/pedido/$id'
    | '/produtos/$slug'
    | '/admin/'
    | '/colecoes/'
    | '/exemplos/'
    | '/produtos/'
    | '/(auth)/curriculum/$id'
    | '/(auth)/training/manage'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/(auth)/arqueacao/'
    | '/(auth)/cadastros/'
    | '/(auth)/curriculum/'
    | '/(auth)/dashboard/'
    | '/(auth)/permissions/'
    | '/(auth)/settings/'
    | '/(auth)/tankages/'
    | '/(auth)/training/'
    | '/admin/estoque/'
    | '/admin/pedidos/'
    | '/admin/produtos/'
    | '/(auth)/tankages/$tankId/$date'
    | '/(auth)/tankages/$tankId/analises-laboratorio'
    | '/(auth)/training/courses/$id'
    | '/(auth)/training/courses/new'
    | '/(auth)/tankages/$tankId/'
    | '/(auth)/training/courses/$id/certificate'
    | '/(auth)/training/courses/$id/manage'
    | '/(auth)/training/courses/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckEmailRoute: typeof CheckEmailRoute
  CheckoutRoute: typeof CheckoutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PoliticaPrivacidadeRoute: typeof PoliticaPrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermosRoute: typeof TermosRoute
  TrocasDevolucoesRoute: typeof TrocasDevolucoesRoute
  TwoFactorRoute: typeof TwoFactorRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ColecoesSlugRoute: typeof ColecoesSlugRoute
  ContaPedidosRoute: typeof ContaPedidosRoute
  CurriculumSubmitRoute: typeof CurriculumSubmitRoute
  ExemplosBodoniRoute: typeof ExemplosBodoniRoute
  ExemplosBossaNovaRoute: typeof ExemplosBossaNovaRoute
  ExemplosEditorialRoute: typeof ExemplosEditorialRoute
  PedidoIdRoute: typeof PedidoIdRoute
  ProdutosSlugRoute: typeof ProdutosSlugRoute
  ColecoesIndexRoute: typeof ColecoesIndexRoute
  ExemplosIndexRoute: typeof ExemplosIndexRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocas-devolucoes': {
      id: '/trocas-devolucoes'
      path: '/trocas-devolucoes'
      fullPath: '/trocas-devolucoes'
      preLoaderRoute: typeof TrocasDevolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidade': {
      id: '/politica-privacidade'
      path: '/politica-privacidade'
      fullPath: '/politica-privacidade'
      preLoaderRoute: typeof PoliticaPrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exemplos/': {
      id: '/exemplos/'
      path: '/exemplos'
      fullPath: '/exemplos/'
      preLoaderRoute: typeof ExemplosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecoes/': {
      id: '/colecoes/'
      path: '/colecoes'
      fullPath: '/colecoes/'
      preLoaderRoute: typeof ColecoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/produtos/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exemplos/editorial': {
      id: '/exemplos/editorial'
      path: '/exemplos/editorial'
      fullPath: '/exemplos/editorial'
      preLoaderRoute: typeof ExemplosEditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exemplos/bossa-nova': {
      id: '/exemplos/bossa-nova'
      path: '/exemplos/bossa-nova'
      fullPath: '/exemplos/bossa-nova'
      preLoaderRoute: typeof ExemplosBossaNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exemplos/bodoni': {
      id: '/exemplos/bodoni'
      path: '/exemplos/bodoni'
      fullPath: '/exemplos/bodoni'
      preLoaderRoute: typeof ExemplosBodoniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/submit': {
      id: '/curriculum/submit'
      path: '/curriculum/submit'
      fullPath: '/curriculum/submit'
      preLoaderRoute: typeof CurriculumSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/pedidos': {
      id: '/conta/pedidos'
      path: '/conta/pedidos'
      fullPath: '/conta/pedidos'
      preLoaderRoute: typeof ContaPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecoes/$slug': {
      id: '/colecoes/$slug'
      path: '/colecoes/$slug'
      fullPath: '/colecoes/$slug'
      preLoaderRoute: typeof ColecoesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/curriculum': {
      id: '/(auth)/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof authCurriculumRouteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/admin/produtos/': {
      id: '/admin/produtos/'
      path: '/produtos'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AdminProdutosIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pedidos/': {
      id: '/admin/pedidos/'
      path: '/pedidos'
      fullPath: '/admin/pedidos/'
      preLoaderRoute: typeof AdminPedidosIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/estoque/': {
      id: '/admin/estoque/'
      path: '/estoque'
      fullPath: '/admin/estoque/'
      preLoaderRoute: typeof AdminEstoqueIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(auth)/training/': {
      id: '/(auth)/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof authTrainingIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/tankages/': {
      id: '/(auth)/tankages/'
      path: '/tankages'
      fullPath: '/tankages/'
      preLoaderRoute: typeof authTankagesIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/settings/': {
      id: '/(auth)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof authSettingsIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/permissions/': {
      id: '/(auth)/permissions/'
      path: '/permissions'
      fullPath: '/permissions/'
      preLoaderRoute: typeof authPermissionsIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/dashboard/': {
      id: '/(auth)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authDashboardIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/curriculum/': {
      id: '/(auth)/curriculum/'
      path: '/'
      fullPath: '/curriculum/'
      preLoaderRoute: typeof authCurriculumIndexRouteImport
      parentRoute: typeof authCurriculumRouteRoute
    }
    '/(auth)/cadastros/': {
      id: '/(auth)/cadastros/'
      path: '/cadastros'
      fullPath: '/cadastros/'
      preLoaderRoute: typeof authCadastrosIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/arqueacao/': {
      id: '/(auth)/arqueacao/'
      path: '/arqueacao'
      fullPath: '/arqueacao/'
      preLoaderRoute: typeof authArqueacaoIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/admin/produtos/novo': {
      id: '/admin/produtos/novo'
      path: '/produtos/novo'
      fullPath: '/admin/produtos/novo'
      preLoaderRoute: typeof AdminProdutosNovoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/produtos/$id': {
      id: '/admin/produtos/$id'
      path: '/produtos/$id'
      fullPath: '/admin/produtos/$id'
      preLoaderRoute: typeof AdminProdutosIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pedidos/$id': {
      id: '/admin/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AdminPedidosIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(auth)/training/manage': {
      id: '/(auth)/training/manage'
      path: '/training/manage'
      fullPath: '/training/manage'
      preLoaderRoute: typeof authTrainingManageRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/curriculum/$id': {
      id: '/(auth)/curriculum/$id'
      path: '/$id'
      fullPath: '/curriculum/$id'
      preLoaderRoute: typeof authCurriculumIdRouteImport
      parentRoute: typeof authCurriculumRouteRoute
    }
    '/(auth)/tankages/$tankId/': {
      id: '/(auth)/tankages/$tankId/'
      path: '/tankages/$tankId'
      fullPath: '/tankages/$tankId/'
      preLoaderRoute: typeof authTankagesTankIdIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/training/courses/new': {
      id: '/(auth)/training/courses/new'
      path: '/training/courses/new'
      fullPath: '/training/courses/new'
      preLoaderRoute: typeof authTrainingCoursesNewRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/training/courses/$id': {
      id: '/(auth)/training/courses/$id'
      path: '/training/courses/$id'
      fullPath: '/training/courses/$id'
      preLoaderRoute: typeof authTrainingCoursesIdRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/tankages/$tankId/analises-laboratorio': {
      id: '/(auth)/tankages/$tankId/analises-laboratorio'
      path: '/tankages/$tankId/analises-laboratorio'
      fullPath: '/tankages/$tankId/analises-laboratorio'
      preLoaderRoute: typeof authTankagesTankIdAnalisesLaboratorioRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/tankages/$tankId/$date': {
      id: '/(auth)/tankages/$tankId/$date'
      path: '/tankages/$tankId/$date'
      fullPath: '/tankages/$tankId/$date'
      preLoaderRoute: typeof authTankagesTankIdDateRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/training/courses/$id/': {
      id: '/(auth)/training/courses/$id/'
      path: '/'
      fullPath: '/training/courses/$id/'
      preLoaderRoute: typeof authTrainingCoursesIdIndexRouteImport
      parentRoute: typeof authTrainingCoursesIdRoute
    }
    '/(auth)/training/courses/$id/manage': {
      id: '/(auth)/training/courses/$id/manage'
      path: '/manage'
      fullPath: '/training/courses/$id/manage'
      preLoaderRoute: typeof authTrainingCoursesIdManageRouteImport
      parentRoute: typeof authTrainingCoursesIdRoute
    }
    '/(auth)/training/courses/$id/certificate': {
      id: '/(auth)/training/courses/$id/certificate'
      path: '/certificate'
      fullPath: '/training/courses/$id/certificate'
      preLoaderRoute: typeof authTrainingCoursesIdCertificateRouteImport
      parentRoute: typeof authTrainingCoursesIdRoute
    }
  }
}

interface authCurriculumRouteRouteChildren {
  authCurriculumIdRoute: typeof authCurriculumIdRoute
  authCurriculumIndexRoute: typeof authCurriculumIndexRoute
}

const authCurriculumRouteRouteChildren: authCurriculumRouteRouteChildren = {
  authCurriculumIdRoute: authCurriculumIdRoute,
  authCurriculumIndexRoute: authCurriculumIndexRoute,
}

const authCurriculumRouteRouteWithChildren =
  authCurriculumRouteRoute._addFileChildren(authCurriculumRouteRouteChildren)

interface authTrainingCoursesIdRouteChildren {
  authTrainingCoursesIdCertificateRoute: typeof authTrainingCoursesIdCertificateRoute
  authTrainingCoursesIdManageRoute: typeof authTrainingCoursesIdManageRoute
  authTrainingCoursesIdIndexRoute: typeof authTrainingCoursesIdIndexRoute
}

const authTrainingCoursesIdRouteChildren: authTrainingCoursesIdRouteChildren = {
  authTrainingCoursesIdCertificateRoute: authTrainingCoursesIdCertificateRoute,
  authTrainingCoursesIdManageRoute: authTrainingCoursesIdManageRoute,
  authTrainingCoursesIdIndexRoute: authTrainingCoursesIdIndexRoute,
}

const authTrainingCoursesIdRouteWithChildren =
  authTrainingCoursesIdRoute._addFileChildren(
    authTrainingCoursesIdRouteChildren,
  )

interface authRouteRouteChildren {
  authCurriculumRouteRoute: typeof authCurriculumRouteRouteWithChildren
  authTrainingManageRoute: typeof authTrainingManageRoute
  authArqueacaoIndexRoute: typeof authArqueacaoIndexRoute
  authCadastrosIndexRoute: typeof authCadastrosIndexRoute
  authDashboardIndexRoute: typeof authDashboardIndexRoute
  authPermissionsIndexRoute: typeof authPermissionsIndexRoute
  authSettingsIndexRoute: typeof authSettingsIndexRoute
  authTankagesIndexRoute: typeof authTankagesIndexRoute
  authTrainingIndexRoute: typeof authTrainingIndexRoute
  authTankagesTankIdDateRoute: typeof authTankagesTankIdDateRoute
  authTankagesTankIdAnalisesLaboratorioRoute: typeof authTankagesTankIdAnalisesLaboratorioRoute
  authTrainingCoursesIdRoute: typeof authTrainingCoursesIdRouteWithChildren
  authTrainingCoursesNewRoute: typeof authTrainingCoursesNewRoute
  authTankagesTankIdIndexRoute: typeof authTankagesTankIdIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authCurriculumRouteRoute: authCurriculumRouteRouteWithChildren,
  authTrainingManageRoute: authTrainingManageRoute,
  authArqueacaoIndexRoute: authArqueacaoIndexRoute,
  authCadastrosIndexRoute: authCadastrosIndexRoute,
  authDashboardIndexRoute: authDashboardIndexRoute,
  authPermissionsIndexRoute: authPermissionsIndexRoute,
  authSettingsIndexRoute: authSettingsIndexRoute,
  authTankagesIndexRoute: authTankagesIndexRoute,
  authTrainingIndexRoute: authTrainingIndexRoute,
  authTankagesTankIdDateRoute: authTankagesTankIdDateRoute,
  authTankagesTankIdAnalisesLaboratorioRoute:
    authTankagesTankIdAnalisesLaboratorioRoute,
  authTrainingCoursesIdRoute: authTrainingCoursesIdRouteWithChildren,
  authTrainingCoursesNewRoute: authTrainingCoursesNewRoute,
  authTankagesTankIdIndexRoute: authTankagesTankIdIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPedidosIdRoute: typeof AdminPedidosIdRoute
  AdminProdutosIdRoute: typeof AdminProdutosIdRoute
  AdminProdutosNovoRoute: typeof AdminProdutosNovoRoute
  AdminEstoqueIndexRoute: typeof AdminEstoqueIndexRoute
  AdminPedidosIndexRoute: typeof AdminPedidosIndexRoute
  AdminProdutosIndexRoute: typeof AdminProdutosIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminPedidosIdRoute: AdminPedidosIdRoute,
  AdminProdutosIdRoute: AdminProdutosIdRoute,
  AdminProdutosNovoRoute: AdminProdutosNovoRoute,
  AdminEstoqueIndexRoute: AdminEstoqueIndexRoute,
  AdminPedidosIndexRoute: AdminPedidosIndexRoute,
  AdminProdutosIndexRoute: AdminProdutosIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckEmailRoute: CheckEmailRoute,
  CheckoutRoute: CheckoutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PoliticaPrivacidadeRoute: PoliticaPrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermosRoute: TermosRoute,
  TrocasDevolucoesRoute: TrocasDevolucoesRoute,
  TwoFactorRoute: TwoFactorRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ColecoesSlugRoute: ColecoesSlugRoute,
  ContaPedidosRoute: ContaPedidosRoute,
  CurriculumSubmitRoute: CurriculumSubmitRoute,
  ExemplosBodoniRoute: ExemplosBodoniRoute,
  ExemplosBossaNovaRoute: ExemplosBossaNovaRoute,
  ExemplosEditorialRoute: ExemplosEditorialRoute,
  PedidoIdRoute: PedidoIdRoute,
  ProdutosSlugRoute: ProdutosSlugRoute,
  ColecoesIndexRoute: ColecoesIndexRoute,
  ExemplosIndexRoute: ExemplosIndexRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
